server:
  port: 3106
spring:
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    #url: jdbc:h2:mem:message;MODE=PostgreSQL
    username: postgres
    password: postgres
    platform: POSTGRESQL
    validation-query: select 1
    connection-test-query: select 1
    test-while-idle: true
    test-on-borrow: true
    time-between-eviction-runs-millis: 60000
    maximum-pool-size: 3
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    driverClassName: org.postgresql.Driver
    #driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    #database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    enabled: true